### ISSUE TITLE
Don't use Abbreviations 

### ISSUE THREAD

**Issue by germanattanasio** [degrim/asp.netcore-watson-visual-recognition#1]
Change VR to visual-recognition or visualRecognition depending on the best practices for asp.net but never use abbreviations.

**Comment by degrim** [comment]
Issue should be fixed with this [commit](https://github.com/degrim/asp.netcore-watson-visual-recognition/commit/20b1a822d5bc2d5589a394ecf76d2cf311a78ec1).

**Comment by germanattanasio** [comment]
You are the real MVP!
